apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: sample-spring-boot-app-openshift2-run-
spec:
  params:
    - name: git-revision
      value: master
  pipelineRef:
    name: sample-spring-boot-app-openshift2
  serviceAccountName: pipeline
  workspaces:
    - name: source-dir
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: sonar-settings
      secret:
        secretName: sonarqube-secret-token
    - configMap:
        name: maven-settings
      name: maven-settings
